
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

development:
  adapter: mysql2
  database: cv_builder_test
  username: root
  password: root
  host: localhost
  port: 5432
  pool: 5
  
test:
  adapter: mysql2
  database: cv_builder_production
  username: root
  password: root
  host: 127.0.0.1

staging:
  adapter: mysql2
  database: cv_builder_staging
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: cv_builder_production
  username: root
  password: root
  host: 127.0.0.1

